//@version=3
// Version 1.0 - feb 2020 - Bas Willemstijn
study(title="EMA-PSAR-ATR-Combo", shorttitle="EMA-PSAR-ATR", overlay=true)

// EMA LINES
dropn(src, n) =>
    na(src[n]) ? na : src

xema(src, len) =>
    mult = 2.0 / (len + 1.0)
    res = na
    res := mult * src + (1.0 - mult) * nz(res[1], src)

length1 = input(9, title="Very Fast Length", minval=1)
length2 = input(21, title="Fast Length", minval=1)
src = input(close, type=source, title="Source")
dropCandles = input(1, minval=0, title="Drop first N candles")

price = dropn(src, dropCandles)

sig1 = xema(price, length1)
sig2 = xema(price, length2)

plot(sig1, title="9 day EMA", color=blue, transp=0, linewidth=1)
plot(sig2, title="21 day EMA", color=red, transp=0, linewidth=1)

//PSAR INDICATOR
start = input(2, minval=0, maxval=10, title="Start - Default = 2 - Multiplied by .01")
increment = input(2, minval=0, maxval=10, title="Step Setting (Sensitivity) - Default = 2 - Multiplied by .01" )
maximum = input(2, minval=1, maxval=10, title="Maximum Step (Sensitivity) - Default = 2 - Multiplied by .10")
sus = input(true, "Show Up Trending Parabolic Sar")
sds = input(true, "Show Down Trending Parabolic Sar")
disc = input(false, title="Start and Step settings are *.01 so 2 = .02 etc, Maximum Step is *.10 so 2 = .2")

startCalc = start * .01
incrementCalc = increment * .01
maximumCalc = maximum * .10

sarUp = sar(startCalc, incrementCalc, maximumCalc)
sarDown = sar(startCalc, incrementCalc, maximumCalc)

colUp = close >= sarDown ? lime : na
colDown = close <= sarUp ? red : na

plot(sus and sarUp ? sarUp : na, title="Up Trending SAR", style=circles, linewidth=4,color=colUp)
plot(sds and sarDown ? sarDown : na, title="Up Trending SAR", style=circles, linewidth=4,color=colDown)

// ATR INDICATOR
length = input(7, minval=1)
src1 = input(close, title="Source")
mult = input(2.0, minval=0.001, maxval=50)
maLen=input(7,title="maLength")
basis = sma(src1, length)
dev = mult * atr(length)
upper = basis + dev
lower = basis - dev
bbr = (src1 - lower)/(upper - lower)
bbe= ema(bbr,maLen)
up =  bbe[1]>bbe and bbe[2]<bbe[1]?bbe:na
bt =  bbe[1]<bbe and bbe[2]>bbe[1]?bbe:na

topH=na(up)==0?highest(3):na
bottomL=na(bt)==0?lowest(3):na

tf= fixnan(topH)
bf =fixnan(bottomL)

btop=close>open?close:open
bbot=close>open?open:close

plot(tf,color=blue,style=circles,linewidth=1,offset=-1,title="Bearish SL")
plot(bf,color=blue,style=circles,linewidth=1,offset=-1,title="Bullish SL")