//@version=3
// Version 1.0 - jan 2020 - Bas Willemstijn
study(title="Exponential Moving Average (5) [Numchuck]", shorttitle="5-EMA [Numchuck]", overlay=true)

dropn(src, n) =>
    na(src[n]) ? na : src

xema(src, len) =>
    mult = 2.0 / (len + 1.0)
    res = na
    res := mult * src + (1.0 - mult) * nz(res[1], src)

length1 = input(9, title="Very Fast Length", minval=1)
length2 = input(21, title="Fast Length", minval=1)
length3 = input(50, title="Slow Length", minval=1)
length4 = input(100, title="Very Slow Length", minval=1)
length5 = input(200, title="Extreme Slow Length", minval=1)
src = input(close, type=source, title="Source")
dropCandles = input(1, minval=0, title="Drop first N candles")

price = dropn(src, dropCandles)

sig1 = xema(price, length1)
sig2 = xema(price, length2)
sig3 = xema(price, length3)
sig4 = xema(price, length4)
sig5 = xema(price, length5)

plot(sig1, title="9 day EMA", color=#b8b42d, transp=0, linewidth=1)
plot(sig2, title="21 day EMA", color=#095256, transp=0, linewidth=1)
plot(sig3, title="50 day EMA", color=#d7263d, transp=0, linewidth=1)
plot(sig4, title="100 day EMA", color=#124e78, transp=0, linewidth=1)
plot(sig5, title="200 day EMA", color=#fbaa29, transp=0, linewidth=1)