study("ADI with DI+, DI- and RSI [Numchuck]", shorttitle="ADX/DI+/DI-/RSI")
// ADI section
adxlen = input(14, title="ADX Smoothing")
dilen = input(14, title="DI Length")
dirmov(len) =>
	up = change(high)
	down = -change(low)
	truerange = rma(tr, len)
	plus = fixnan(100 * rma(up > down and up > 0 ? up : 0, len) / truerange)
	minus = fixnan(100 * rma(down > up and down > 0 ? down : 0, len) / truerange)
	[plus, minus]

adx(dilen, adxlen) => 
	[plus, minus] = dirmov(dilen)
	sum = plus + minus
	adx = 100 * rma(abs(plus - minus) / (sum == 0 ? 1 : sum), adxlen)

adxHigh(dilen, adxlen) => 
	[plus, minus] = dirmov(dilen)
	plus
	
adxLow(dilen, adxlen) => 
	[plus, minus] = dirmov(dilen)
	minus
    
sig = adx(dilen, adxlen)
sigHigh = adxHigh(dilen, adxlen)
sigLow = adxLow(dilen, adxlen)

// RSI section
src = close, 
len1 = input(14, minval=1, title="RSI Length")
up = rma(max(change(src), 0), len1)
down = rma(-min(change(src), 0), len1)
rsi = down == 0 ? 100 : up == 0 ? 0 : 100 - (100 / (1 + up / down))

// Plot section
plot(sig, title="ADX", color=blue, transp=0, linewidth=2)
plot(sigHigh, title="DI+", color=green, transp=0, linewidth=2)
plot(sigLow, title="DI-", color=red, transp=0, linewidth=2)
plot(rsi, title="RSI", style=line, linewidth=1, color=#474747)
band1 = hline(70, title="RSI Upper",  color=#474747, linewidth=1, linestyle=dashed)
band2 = hline(50, title="RSI Middle", color=#474747, linewidth=1, linestyle=dashed)
band3 = hline(30, title="RSI Lower", color=#474747, linewidth=1, linestyle=dashed)
band4 = hline(20, title="ADI line", color=red, linewidth=2)
