study(title="Ichi-PSAR-ATR", shorttitle="Ichi-PSAR-ATR", overlay=true)
start = input(0.02)
increment = input(0.05)
maximum = input(0.2)
sar = sar(start, increment, maximum)
length = input(20)
smaclose= sma(close, 3*length)
smahigh = sma(high, 3*length)
smalow = sma(low, 3*length)
mult = input(4)
atr_ = atr(length)
max1 = max(nz(max_[1]), close)
min1 = min(nz(min_[1]), close)
is_uptrend_prev = nz(is_uptrend[1], true)
stop = is_uptrend_prev ? max1 - mult * atr_ : min1 + mult * atr_
vstop_prev = nz(vstop[1])
vstop_prev2 = nz(vstop[2])
vstop1 = is_uptrend_prev ? min(max(vstop_prev, stop), sar): max(min(vstop_prev, stop), sar)
is_uptrend = close - vstop1 >= 0
is_trend_changed = is_uptrend != is_uptrend_prev
max_ = is_trend_changed ? close : max1
min_ = is_trend_changed ? close : min1
vstop = is_trend_changed ? is_uptrend ? max(max_ - mult * atr_, sar) : min(min_ + mult * atr_, sar) : vstop1
p1 = plot(vstop, color = is_uptrend ? aqua : fuchsia, style = line, linewidth=2)
sma = is_uptrend?smaclose : smaclose
p2 = plot(sma, color = white, linewidth=2)

// Ichimoku
conversionPeriods = input(20, minval=1, title="Conversion Line Periods"),
basePeriods = input(60, minval=1, title="Base Line Periods") // 21 weeks MA because day price seems to respect this line
laggingSpan2Periods = input(120, minval=1, title="Lagging Span 2 Periods"),
displacement = input(26, minval=1, title="Displacement")

donchian(len) => avg(lowest(len), highest(len))

conversionLine = donchian(conversionPeriods)
baseLine = donchian(basePeriods)
leadLine1 = avg(conversionLine, baseLine)
leadLine2 = donchian(laggingSpan2Periods)

plot(conversionLine, color=#0496ff, title="Conversion Line")
plot(baseLine, color=#991515, title="Base Line")
plot(close, offset = -displacement + 1, color=#459915, title="Lagging Span")

p1a = plot(leadLine1, offset = displacement - 1, color=green,
 title="Lead 1")
p2a = plot(leadLine2, offset = displacement - 1, color=red, 
 title="Lead 2")
fill(p1a, p2a, color = leadLine1 > leadLine2 ? green : red)