//Created by ChrisMoody 7-21-2014
//Daily, Weekly, Monthly, Quarterly, Yearly Projected Highs and Lows 
//Obtained formula from Larry Williams, original formula from Owen Taylor
// Heard this story from Larry Williams…the trader who holds the record for winning the U.S. Trading Championship by turning $10K in to 2 Million.
// A trader named Owen Taylor developed this formula as a Floor Trader before to calculate the Projected High and Low of the next day.
// The formula worked so well…Owen charged other Traders 1K to get it.
// I was pretty impressed with the results…so I coded it for the Weekly, Monthly, Quarterly, and Yearly Projected High Low.
// While Owen considered these levels to be major support and resistance , Larry has developed many strategies based on the Breakout of the Projected High Low.
// Therefore I coded it so the Levels would plot Yellow, and change to Green if the Projected High was taken out, and Red if the Projected Low was taken out.

***I’ve noticed on many instruments, Stocks, Index’s, Forex etc., depending on the instrument it works great as Support/Resistance or Breakouts.
***On a Daily Chart put the Quarterly and Yearly levels on SPY and EURUSD and go back about 10 years. Levels are pretty accurate.
study(title="CM_OldSchool_Projected_High_Low", shorttitle="CM_OS_Proj_H_L", overlay=true) 
sd = input(true, title="Show Daily Projected High Low?")
sw = input(false, title="Show Weekly Projected High Low?")
sm = input(false, title="Show Monthly Projected High Low?")
sq = input(false, title="Show Quarterly Projected High Low?")
sy = input(false, title="Show Yearly Projected High Low?")

pf = (hlc3) *2
pl = pf - high
ph = pf - low
 
dtime_pf = security(tickerid, 'D', pf[1]) 
dtime_pl = security(tickerid, 'D', pl[1]) 
dtime_ph = security(tickerid, 'D', ph[1]) 
 
pcolor_pl = close < dtime_pl ? red : yellow
pcolor_ph = close > dtime_ph ? lime : yellow

//Daily Projected High Low
offs_daily = 0 
plot(sd and dtime_pl ? dtime_pl : na, title="Daily Projected Low",style=circles, color=pcolor_pl ,linewidth=3) 
plot(sd and dtime_ph ? dtime_ph : na, title="Daily Projected High",style=circles, color=pcolor_ph ,linewidth=3) 

//Weekly Projected High Low 
wtime_pf = security(tickerid, 'W', pf[1]) 
wtime_pl = security(tickerid, 'W', pl[1]) 
wtime_ph = security(tickerid, 'W', ph[1]) 

wcolor_pl = close < wtime_pl ? red : yellow
wcolor_ph = close > wtime_ph ? lime : yellow

plot(sw and wtime_pl ? wtime_pl : na, title="Weekly Projected Low",style=circles, color=wcolor_pl,linewidth=4) 
plot(sw and wtime_ph ? wtime_ph : na, title="Weekly Projected High",style=circles, color=wcolor_ph,linewidth=4) 

//Monthly Projected High Low 
mtime_pf = security(tickerid, 'M', pf[1]) 
mtime_pl = security(tickerid, 'M', pl[1]) 
mtime_ph = security(tickerid, 'M', ph[1]) 

mcolor_pl = close < mtime_pl ? red : yellow
mcolor_ph = close > mtime_ph ? lime : yellow

plot(sm and mtime_pl ? mtime_pl : na, title="Monthly Projected Low",style=cross, color=mcolor_pl,linewidth=3) 
plot(sm and mtime_ph ? mtime_ph : na, title="Monthly Projected High",style=cross, color=mcolor_ph,linewidth=3) 

//Quarterly Projected High Low 
qtime_pf = security(tickerid, '3M', pf[1]) 
qtime_pl = security(tickerid, '3M', pl[1])
qtime_ph = security(tickerid, '3M', ph[1])

qcolor_pl = close < qtime_pl ? red : yellow
qcolor_ph = close > qtime_ph ? lime : yellow

//Quarterly Projected High Low 
plot(sq and qtime_pl ? qtime_pl : na, title="Quarterly Projected Low",style=cross, color=qcolor_pl,linewidth=3) 
plot(sq and qtime_ph ? qtime_ph : na, title="Quarterly Projected High",style=cross, color=qcolor_ph,linewidth=3) 

//Yearly Projected High Low 
ytime_pf = security(tickerid, '12M', pf[1]) 
ytime_pl = security(tickerid, '12M', pl[1])
ytime_ph = security(tickerid, '12M', ph[1])

ycolor_pl = close < ytime_pl ? red : yellow
ycolor_ph = close > ytime_ph ? lime : yellow

//Yearly Pivots Plots
plot(sy and ytime_pl ? ytime_pl : na, title="Yearly Projected Low",style=cross, color=ycolor_pl,linewidth=3) 
plot(sy and ytime_ph ? ytime_ph : na, title="Yearly Projected High",style=cross, color=ycolor_ph,linewidth=3) 
