study(title="Ichimoku EMA Bands", shorttitle="IchiEMA", overlay=true)

ATRlength = input(200, minval=1)
ATRMult = input(2.272, minval=1)

ATR = rma(tr(true), ATRlength)

len = input(26, minval=1, title="EMA Length")
src = input(close, title="Source")
out = ema(src, len)
plot(out, title="EMA", color=orange,transp=85)

emaup = out+(ATR*ATRMult)
emadw = out-(ATR*ATRMult)

plot(emaup, title="EMAUP", color=red)
plot(emadw, title="EMADW", color=green)

conversionPeriods = input(5, minval=1),
basePeriods = input(26, minval=1)
laggingSpan2Periods = input(52, minval=1),
displacement = input(26, minval=1)

donchian(len) => avg(lowest(len), highest(len))

conversionLine = donchian(conversionPeriods)
baseLine = donchian(basePeriods)
leadLine1 = avg(conversionLine, baseLine)
leadLine2 = donchian(laggingSpan2Periods)

kjuncol = conversionLine > baseLine ? blue : conversionLine < baseLine ? red : orange

plot(conversionLine, color=red, title="Conversion Line")
plot(baseLine, color=kjuncol,linewidth=2,transp=5, title="Base Line")


p1 = plot(leadLine1, offset = displacement, color=green,transp=85,
    title="Lead 1")
p2 = plot(leadLine2, offset = displacement, color=red,transp=85,  
    title="Lead 2")
fill(p1, p2,silver)

