study(title="Snabbel_RSI_EMA", shorttitle="SNAB_RSI_EMA_", overlay=false)
src = close, 
len = input(14, minval=1, title="RSI Length")
len2 = input(12, minval=1, title="EMA of RSI Length")
up = rma(max(change(src), 0), len)
down = rma(-min(change(src), 0), len)
rsi = down == 0 ? 100 : up == 0 ? 0 : 100 - (100 / (1 + up / down))
emaRSI = ema(rsi,len2)

plot(rsi, title="RSI", style=line, linewidth=2, color=black)
plot(emaRSI, title="EMA of RSI", style=line, linewidth=2, color=red)
band1 = hline(80, title="Upper Line", linestyle=dashed, linewidth=1, color=red)
band0 = hline(20, title="Lower Line", linestyle=dashed, linewidth=1, color=lime)
band2 = hline(45, title="Upper Line", linestyle=dashed, linewidth=1, color=gray)
band3 = hline(50, title="Lower Line", linestyle=dashed, linewidth=1, color=black)
band4 = hline(55, title="Lower Line", linestyle=dashed, linewidth=1, color=gray)
